"""Static fix templates for the 3 non-LLM analyzers.

The LLM analyzers (brand_clarity, content_citability, eeat_signals, competitive,
factual_density) get their fix dict generated by ``mvp_a_audit.logic.generate_recommendations``
which calls Claude with ``prompts/geo_audit/recommendations.txt``.

The 3 deterministic analyzers (crawler_access, llms_txt, schema_markup) get
their fix dict here — no LLM cost, no latency, fully reproducible. Their
``details`` already contain enough structured data to assemble production-
ready snippets directly.

Unified fix schema (same shape from static + LLM paths so the PDF
renderer can treat them identically):

    {
        "title":        str,    # ≤ 8 words
        "why_matters":  str,    # 1 sentence
        "how_to_fix":   str,    # 2-3 sentences
        "code_snippet": str,    # ready-to-paste, may be ""
        "difficulty":   str,    # "Easy (X)" / "Medium (X)" / "Hard (X)"
        "impact":       str,    # "High" / "Medium" / "Low"
    }
"""

from __future__ import annotations

from urllib.parse import urlparse

# ── Constants shared with the analyzers ──────────────────────────────────────

# Mirror of llms_txt._CORE_SECTIONS (kept in sync manually — both files
# describe the same llms.txt spec, so they don't drift often).
_LLMS_CORE_SECTIONS = ["## about", "## products", "## use", "## do not", "## contact", "## verified"]

# Mirror of schema_markup._CORE_TYPES.
_SCHEMA_CORE_TYPES = ["Organization", "Product", "FAQPage", "BreadcrumbList"]

# Friendly explanation of why each dimension matters — used by both static
# templates AND the LLM-fix adapter so the PDF can show a "Why this matters"
# line for every dimension regardless of fix source.
WHY_MATTERS: dict[str, str] = {
    "crawler_access":     "If AI crawlers can't access your site, ChatGPT, Claude, and Perplexity simply cannot include you in answers — even if your content is perfect.",
    "llms_txt":           "llms.txt is the emerging standard for LLM site discovery — major AI assistants check it before crawling, so a present, well-structured file is the cheapest visibility win available.",
    "schema_markup":      "Schema.org JSON-LD lets AI parse your content structurally instead of guessing — it dramatically improves the accuracy of how your brand and products are summarized.",
    "brand_clarity":      "AI assistants need a clear, citable understanding of what your brand does. Vague positioning means AI paraphrases incorrectly or skips you entirely.",
    "content_citability": "AI cites paragraphs that contain self-contained facts. Marketing copy with no specific numbers or named entities gets paraphrased without attribution — costing you brand mentions.",
    "eeat_signals":       "AI assistants weight Experience, Expertise, Authoritativeness, and Trustworthiness when choosing sources to cite. Weak E-E-A-T means weaker AI recommendations.",
    "competitive":        "When users ask AI 'X vs Y' or 'best X for Y', AI surfaces brands with comparison and positioning content. Without it you're invisible in head-to-head answers.",
    "factual_density":    "Marketing-heavy copy gets paraphrased; fact-rich copy gets cited verbatim with attribution. Density of specifics is the single biggest lever for AI mentions.",
}


def _weight_to_impact(weight: float) -> str:
    if weight >= 0.15:
        return "High"
    if weight >= 0.10:
        return "Medium"
    return "Low"


def _origin(url: str) -> str:
    """Return ``scheme://host`` (no path) for use in snippet templates."""
    try:
        p = urlparse(url)
        if p.scheme and p.netloc:
            return f"{p.scheme}://{p.netloc}"
    except Exception:
        pass
    return url.rstrip("/") if url else "https://your-site.com"


# ── Template 1: crawler_access ───────────────────────────────────────────────

_BOT_USER_AGENTS = ["GPTBot", "ClaudeBot", "PerplexityBot", "Google-Extended"]


def generate_fix_crawler_access(details: dict, brand_name: str, url: str) -> dict:
    disallowed = list(details.get("disallowed", []) or [])
    not_mentioned = list(details.get("not_mentioned", []) or [])

    targets = disallowed + not_mentioned
    if not targets:
        # All 4 bots explicitly allowed — nothing to fix
        return {
            "title":        "Maintain explicit crawler access",
            "why_matters":  WHY_MATTERS["crawler_access"],
            "how_to_fix":   "Your robots.txt already allows all major AI crawlers. Keep monitoring as new bots launch — add explicit Allow rules for each new agent rather than relying on default permission.",
            "code_snippet": "# Already configured correctly — no changes needed.\n# Re-check this quarterly as new AI bots launch.",
            "difficulty":   "Easy (5 min)",
            "impact":       "Medium",
        }

    # Build robots.txt block — one User-agent per target with Allow: /
    lines = ["# robots.txt — at your site root (https://example.com/robots.txt)",
             "# Append (or replace) the AI-crawler section with the following:",
             ""]
    for bot in targets:
        lines.append(f"User-agent: {bot}")
        lines.append("Allow: /")
        lines.append("")
    # Trailing best-practice: explicit Sitemap reference
    lines.append(f"Sitemap: {_origin(url)}/sitemap.xml")

    code_snippet = "\n".join(lines)

    n_blocked = len(disallowed)
    n_missing = len(not_mentioned)
    parts = []
    if n_blocked:
        parts.append(f"Remove or relax the existing Disallow lines for {', '.join(disallowed)} (currently blocked).")
    if n_missing:
        parts.append(f"Add explicit Allow blocks for {', '.join(not_mentioned)} so each bot has unambiguous permission.")
    parts.append("Deploy by editing your site's robots.txt file and uploading it to the web root — no application restart needed.")
    how_to_fix = " ".join(parts)

    return {
        "title":        f"Allow {len(targets)} AI crawler(s) in robots.txt",
        "why_matters":  WHY_MATTERS["crawler_access"],
        "how_to_fix":   how_to_fix,
        "code_snippet": code_snippet,
        "difficulty":   "Easy (10 min)",
        "impact":       _weight_to_impact(0.10),
    }


# ── Template 2: llms_txt ─────────────────────────────────────────────────────

_LLMS_SECTION_HINTS: dict[str, str] = {
    "## about":    "Two-paragraph description of what {brand} does and who it serves. Pull from your About page.",
    "## products": "Bulleted list of your main products/services with one-line value props each.",
    "## use":      "Concrete example use cases, scenarios, or workflows where customers use {brand}.",
    "## do not":   "Honest list of cases where {brand} is NOT a good fit. Counterintuitively, this builds trust.",
    "## contact":  "Email + sales link + support URL. Public, machine-readable contact info.",
    "## verified": "List of authoritative URLs (Wikipedia, news articles, press releases) where claims can be verified.",
}


def generate_fix_llms_txt(details: dict, brand_name: str, url: str) -> dict:
    sections_found = [s.lower() for s in (details.get("sections_found") or [])]
    missing = [s for s in _LLMS_CORE_SECTIONS if s not in sections_found]
    word_count = int(details.get("word_count") or 0)

    brand = brand_name or "[YOUR_BRAND_NAME]"
    site = _origin(url)

    # Build a complete llms.txt template — covering missing sections + the
    # full skeleton if word_count is too low.
    lines = [
        f"# {brand}",
        "",
        f"> One-sentence value prop. e.g. \"{brand} is a [category] for [audience] that [main benefit].\"",
        "",
    ]
    for section in _LLMS_CORE_SECTIONS:
        # Always include the full skeleton when starting from scratch.
        # When only some sections are missing, mark missing ones explicitly.
        is_missing = section in missing
        hint = _LLMS_SECTION_HINTS[section].replace("{brand}", brand)
        marker = " (ADD THIS)" if is_missing and word_count > 50 else ""
        lines.append(f"{section.capitalize()}{marker}")
        lines.append("")
        lines.append(hint)
        lines.append("")

    code_snippet = "\n".join(lines).rstrip() + "\n"

    if word_count == 0:
        scope = "Create an llms.txt file from scratch — there is currently none at the site root."
        difficulty = "Medium (1 hour)"
    elif missing:
        scope = f"Add the {len(missing)} missing section(s) to your existing llms.txt: {', '.join(missing)}."
        difficulty = "Easy (20 min)"
    else:
        scope = "All core sections are present — expand each section with more specific facts (named products, numbers, customer quotes) to raise the score above 80."
        difficulty = "Easy (15 min)"

    how_to_fix = (
        f"{scope} "
        "Upload the resulting file to your web root so it's served at "
        f"{site}/llms.txt with content-type text/plain. Verify with curl after deploy."
    )

    return {
        "title":        "Publish a complete llms.txt at site root",
        "why_matters":  WHY_MATTERS["llms_txt"],
        "how_to_fix":   how_to_fix,
        "code_snippet": code_snippet,
        "difficulty":   difficulty,
        "impact":       _weight_to_impact(0.08),
    }


# ── Template 3: schema_markup ────────────────────────────────────────────────

def _schema_organization(brand: str, site: str) -> str:
    return (
        '<script type="application/ld+json">\n'
        "{\n"
        '  "@context": "https://schema.org",\n'
        '  "@type": "Organization",\n'
        f'  "name": "{brand}",\n'
        f'  "url": "{site}",\n'
        f'  "logo": "{site}/logo.png",\n'
        '  "sameAs": [\n'
        '    "https://twitter.com/[YOUR_HANDLE]",\n'
        '    "https://www.linkedin.com/company/[YOUR_HANDLE]"\n'
        "  ]\n"
        "}\n"
        "</script>"
    )


def _schema_product(brand: str, site: str) -> str:
    return (
        '<script type="application/ld+json">\n'
        "{\n"
        '  "@context": "https://schema.org",\n'
        '  "@type": "Product",\n'
        '  "name": "[YOUR_PRODUCT_NAME]",\n'
        '  "description": "[ONE_LINE_PRODUCT_DESCRIPTION]",\n'
        f'  "brand": {{ "@type": "Brand", "name": "{brand}" }},\n'
        '  "offers": {\n'
        '    "@type": "Offer",\n'
        '    "price": "[PRICE]",\n'
        '    "priceCurrency": "USD",\n'
        '    "availability": "https://schema.org/InStock"\n'
        "  }\n"
        "}\n"
        "</script>"
    )


def _schema_faq(brand: str, site: str) -> str:
    return (
        '<script type="application/ld+json">\n'
        "{\n"
        '  "@context": "https://schema.org",\n'
        '  "@type": "FAQPage",\n'
        '  "mainEntity": [\n'
        "    {\n"
        '      "@type": "Question",\n'
        '      "name": "[QUESTION_1]",\n'
        '      "acceptedAnswer": {\n'
        '        "@type": "Answer",\n'
        '        "text": "[ANSWER_1]"\n'
        "      }\n"
        "    },\n"
        "    {\n"
        '      "@type": "Question",\n'
        '      "name": "[QUESTION_2]",\n'
        '      "acceptedAnswer": {\n'
        '        "@type": "Answer",\n'
        '        "text": "[ANSWER_2]"\n'
        "      }\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "</script>"
    )


def _schema_breadcrumb(brand: str, site: str) -> str:
    return (
        '<script type="application/ld+json">\n'
        "{\n"
        '  "@context": "https://schema.org",\n'
        '  "@type": "BreadcrumbList",\n'
        '  "itemListElement": [\n'
        "    {\n"
        '      "@type": "ListItem",\n'
        '      "position": 1,\n'
        '      "name": "Home",\n'
        f'      "item": "{site}/"\n'
        "    },\n"
        "    {\n"
        '      "@type": "ListItem",\n'
        '      "position": 2,\n'
        '      "name": "[CATEGORY_NAME]",\n'
        f'      "item": "{site}/[CATEGORY_SLUG]"\n'
        "    }\n"
        "  ]\n"
        "}\n"
        "</script>"
    )


_SCHEMA_TEMPLATE_FUNCS = {
    "Organization":    _schema_organization,
    "Product":         _schema_product,
    "FAQPage":         _schema_faq,
    "BreadcrumbList":  _schema_breadcrumb,
}


def generate_fix_schema_markup(details: dict, brand_name: str, url: str) -> dict:
    found = set(details.get("found_core_types") or [])
    checked = list(details.get("core_types_checked") or _SCHEMA_CORE_TYPES)
    missing = [t for t in checked if t not in found]

    brand = brand_name or "[YOUR_BRAND_NAME]"
    site = _origin(url)

    if not missing:
        return {
            "title":        "Validate existing schema with Google Rich Results",
            "why_matters":  WHY_MATTERS["schema_markup"],
            "how_to_fix":   "All 4 core Schema.org types are present. Run https://search.google.com/test/rich-results on each page type to validate they parse without errors — then expand to product-level coverage on all SKU pages.",
            "code_snippet": "# All core types found. Test each page at:\n# https://search.google.com/test/rich-results",
            "difficulty":   "Easy (15 min)",
            "impact":       "Medium",
        }

    blocks = []
    for t in missing:
        builder = _SCHEMA_TEMPLATE_FUNCS.get(t)
        if builder:
            blocks.append(f"<!-- {t} (add to homepage <head>) -->")
            blocks.append(builder(brand, site))
            blocks.append("")
    code_snippet = "\n".join(blocks).rstrip() + "\n"

    how_to_fix = (
        f"Add the {len(missing)} missing JSON-LD block(s) to your homepage's <head> tag: "
        f"{', '.join(missing)}. "
        "Replace placeholders in square brackets with your real values. "
        "Validate at https://search.google.com/test/rich-results after deploy."
    )

    return {
        "title":        f"Add {len(missing)} missing Schema.org type(s)",
        "why_matters":  WHY_MATTERS["schema_markup"],
        "how_to_fix":   how_to_fix,
        "code_snippet": code_snippet,
        "difficulty":   "Medium (1 hour)",
        "impact":       _weight_to_impact(0.12),
    }


# ── Dispatcher ───────────────────────────────────────────────────────────────

_TEMPLATES = {
    "crawler_access":  generate_fix_crawler_access,
    "llms_txt":        generate_fix_llms_txt,
    "schema_markup":   generate_fix_schema_markup,
}


def generate_static_fix(
    dimension: str, details: dict, brand_name: str, url: str
) -> dict | None:
    """Return a unified-schema fix dict for static dimensions, else ``None``.

    Returns ``None`` (not a raise) if ``dimension`` is one of the LLM-handled
    dimensions or if template generation fails — callers fall back to the
    LLM path.
    """
    func = _TEMPLATES.get(dimension)
    if func is None:
        return None
    try:
        return func(details or {}, brand_name or "", url or "")
    except Exception as exc:
        print(f"[fix_templates] {dimension} template failed: {exc}", flush=True)
        return None
